/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.EcoSystem;
import Business.Order.Order;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jayatipatel
 */
public class DeliveryManViewOrders extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryManViewOrders
     */
    EcoSystem es;
    String username;
    public DeliveryManViewOrders(EcoSystem es, String username) {
        initComponents();
        this.es=es;
        this.username=username;
        ArrayList<Order> orders = new ArrayList<>();
        System.out.println(this.es.getDeliveryManDirectory().searchDeliveryMan(username).getName());
        System.out.println(this.es.getOrderDirectory().getOrderList().size());
        orders = this.es.getOrderDirectory().deliveryManOrders(this.es.getDeliveryManDirectory().searchDeliveryMan(username));
        System.out.println(orders.size());
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<orders.size(); i++){
            row[0] = orders.get(i).getCustomer().getName();
            row[1] = orders.get(i).getRestaurant().getName();
            row[2] = orders.get(i).getStatus().toString();
            row[3] = orders.get(i).getOrderDate().toString();
            if(orders.get(i).getCommentList()==null){
                row[4] = "NoComments";
            }
            else{
                row[4] = orders.get(i).getCommentList().toString();
            }
            if(orders.get(i).getOrderList()==null){
                row[5] = "NotOrderedyet";
            }
            else{
                row[5] = orders.get(i).getOrderList().toString();
            }
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("View Orders");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Restaurant", "Status", "OrderDate", "OrderList", "Comments"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
