/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Order.Order;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jayatipatel
 */
public class CustomerViewOrders extends javax.swing.JPanel {

    /**
     * Creates new form CustomerViewOrders
     */
    EcoSystem es;
    String username;
    public CustomerViewOrders(EcoSystem es, String username) {
        initComponents();
        this.es=es;
        this.username=username;
        ArrayList<Order> orders = new ArrayList<>();
        System.out.println(this.es.getCustomerDirectory().searchCusotmer(this.username).getName());
        System.out.println(this.es.getOrderDirectory().getOrderList().size());
        orders = this.es.getOrderDirectory().customerOrders(this.es.getCustomerDirectory().searchCusotmer(this.username));
        System.out.println(orders.size());
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<orders.size(); i++){
            row[0] = orders.get(i).getRestaurant().getName();
            if(orders.get(i).getDeliveryMan()==null){
                row[1] = "NotAssignedYet";
            }
            else{
                row[1] = orders.get(i).getDeliveryMan().getName();
            }
            row[2] = orders.get(i).getStatus().toString();
            row[3] = orders.get(i).getOrderDate().toString();
            if(orders.get(i).getOrderList()==null){
                row[4] = "NotOrderedyet";
            }
            else{
                row[4] = orders.get(i).getOrderList().toString();
            }
            if(orders.get(i).getCommentList()==null){
                row[5] = "NoComments";
            }
            else{
                row[5] = orders.get(i).getCommentList().toString();
            }
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant", "DeliveryMan", "Status", "Order Date", "Items", "Comments"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("All Orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
